# Site settings
title: "Chicago Pro Movers"
description: "Professional moving services in Chicago. Licensed, insured, and trusted by thousands. Get your move done right with Chicago's premier moving company."
baseurl: ""
url: "https://chicago-promovers.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  services:
    output: true
    permalink: /services/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.gemspec"
  - "*.gem"

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: "Chicago Pro Movers"
lang: en

# Contact info
contact:
  phone: "(312) 555-MOVE"
  email: "info@chicago-promovers.com"
  address: "Chicago, IL"
  zip_codes:
    - "60601"
    - "60602"
    - "60603"
    - "60604"
    - "60605"
    - "60606"
    - "60607"
    - "60608"
    - "60609"
    - "60610"
    - "60611"
    - "60612"
    - "60613"
    - "60614"
    - "60615"
    - "60616"
    - "60617"
    - "60618"
    - "60619"
    - "60620"
    - "60621"
    - "60622"
    - "60623"
    - "60624"
    - "60625"
    - "60626"
    - "60628"
    - "60629"
    - "60630"
    - "60631"
    - "60632"
    - "60633"
    - "60634"
    - "60636"
    - "60637"
    - "60638"
    - "60639"
    - "60640"
    - "60641"
    - "60642"
    - "60643"
    - "60644"
    - "60645"
    - "60646"
    - "60647"
    - "60649"
    - "60651"
    - "60652"
    - "60653"
    - "60654"
    - "60655"
    - "60656"
    - "60657"
    - "60659"
    - "60660"
    - "60661"
    - "60663"
    - "60664"
    - "60665"
    - "60667"
    - "60668"
    - "60669"
    - "60670"
    - "60671"
    - "60672"
    - "60673"
    - "60674"
    - "60675"
    - "60677"
    - "60678"
    - "60679"
    - "60680"
    - "60681"
    - "60682"
    - "60684"
    - "60685"
    - "60686"
    - "60687"
    - "60688"
    - "60689"
    - "60690"
    - "60691"
    - "60693"
    - "60694"
    - "60695"
    - "60696"
    - "60697"
    - "60699"
    - "60701"

# Service areas
service_areas:
  - "Downtown Chicago"
  - "The Loop"
  - "River North"
  - "Lincoln Park"
  - "Lakeview"
  - "Wicker Park"
  - "Bucktown"
  - "Logan Square"
  - "West Loop"
  - "South Loop"
  - "Old Town"
  - "Gold Coast"
  - "Streeterville"
  - "Rogers Park"
  - "Edgewater"
  - "Uptown"
  - "Andersonville"
  - "Roscoe Village"
  - "North Center"
  - "Avondale"
  - "Irving Park"
  - "Albany Park"
  - "Portage Park"
  - "Jefferson Park"
  - "Forest Glen"
  - "North Park"
  - "Norwood Park"
  - "Dunning"
  - "Montclare"
  - "Belmont Cragin"
  - "Hermosa"
  - "Logan Square"
  - "Humboldt Park"
  - "West Town"
  - "Austin"
  - "West Garfield Park"
  - "East Garfield Park"
  - "Near West Side"
  - "North Lawndale"
  - "South Lawndale"
  - "Lower West Side"
  - "Armour Square"
  - "Douglas"
  - "Oakland"
  - "Fuller Park"
  - "Grand Boulevard"
  - "Kenwood"
  - "Washington Park"
  - "Hyde Park"
  - "Woodlawn"
  - "South Shore"
  - "Chatham"
  - "Avalon Park"
  - "South Chicago"
  - "Burnside"
  - "Calumet Heights"
  - "Roseland"
  - "Pullman"
  - "South Deering"
  - "East Side"
  - "Hegewisch"
  - "Garfield Ridge"
  - "Archer Heights"
  - "Brighton Park"
  - "McKinley Park"
  - "Bridgeport"
  - "New City"
  - "West Elsdon"
  - "Gage Park"
  - "Clearing"
  - "West Lawn"
  - "Chicago Lawn"
  - "West Englewood"
  - "Englewood"
  - "Greater Grand Crossing"
  - "Ashburn"
  - "Auburn Gresham"
  - "Beverly"
  - "Washington Heights"
  - "Mount Greenwood"
  - "Morgan Park"

# Social media
social:
  facebook: "https://facebook.com/chicagopromovers"
  instagram: "https://instagram.com/chicagopromovers"
  twitter: "https://twitter.com/chicagopromovers"
  yelp: "https://yelp.com/chicagopromovers"
